### ISSUE TITLE
Array to string conversion (notice on php 5.4)

### ISSUE THREAD

**Issue by jrencz** [diem-project/symfony#4]
Notice: Array to string conversion in lib/vendor/diem/symfony/lib/widget/sfWidgetFormSelectCheckbox.class.php on line 105

it's solved in more recent version of symfony (1.4.17)
Could you please merge changes form 1.4.20 to diem symfony?

**Comment by 4levels** [comment]
Fixed in latest merge from symfony/symfony1 version 1.4.20
